export const loadMorePokemon = {
  count: 1279,
  next: 'https://pokeapi.co/api/v2/pokemon?offset=120&limit=20',
  previous: 'https://pokeapi.co/api/v2/pokemon?offset=80&limit=20',
  results: [
    { name: 'electrode', url: 'https://pokeapi.co/api/v2/pokemon/101/' },
    { name: 'exeggcute', url: 'https://pokeapi.co/api/v2/pokemon/102/' },
    { name: 'exeggutor', url: 'https://pokeapi.co/api/v2/pokemon/103/' },
    { name: 'cubone', url: 'https://pokeapi.co/api/v2/pokemon/104/' },
    { name: 'marowak', url: 'https://pokeapi.co/api/v2/pokemon/105/' },
    { name: 'hitmonlee', url: 'https://pokeapi.co/api/v2/pokemon/106/' },
    { name: 'hitmonchan', url: 'https://pokeapi.co/api/v2/pokemon/107/' },
    { name: 'lickitung', url: 'https://pokeapi.co/api/v2/pokemon/108/' },
    { name: 'koffing', url: 'https://pokeapi.co/api/v2/pokemon/109/' },
    { name: 'weezing', url: 'https://pokeapi.co/api/v2/pokemon/110/' },
    { name: 'rhyhorn', url: 'https://pokeapi.co/api/v2/pokemon/111/' },
    { name: 'rhydon', url: 'https://pokeapi.co/api/v2/pokemon/112/' },
    { name: 'chansey', url: 'https://pokeapi.co/api/v2/pokemon/113/' },
    { name: 'tangela', url: 'https://pokeapi.co/api/v2/pokemon/114/' },
    { name: 'kangaskhan', url: 'https://pokeapi.co/api/v2/pokemon/115/' },
    { name: 'horsea', url: 'https://pokeapi.co/api/v2/pokemon/116/' },
    { name: 'seadra', url: 'https://pokeapi.co/api/v2/pokemon/117/' },
    { name: 'goldeen', url: 'https://pokeapi.co/api/v2/pokemon/118/' },
    { name: 'seaking', url: 'https://pokeapi.co/api/v2/pokemon/119/' },
    { name: 'staryu', url: 'https://pokeapi.co/api/v2/pokemon/120/' },
  ],
}
