//
describe('first visit', () => {
  it('works', () => {
    cy.visit('localhost:3001')
    cy.contains('Search').click()
    cy.url().should('eq', 'http://localhost:3001/search')
    cy.get('input').type('pikachu{enter}')
    cy.wait(500).contains('Pikachu')
    cy.get('input').clear().type('cher{enter}')
    cy.wait(500).contains('Could not find pokemon')
    cy.get('input').clear().type('1{enter}').wait(500)
    cy.contains('Bulbasaur')
    cy.contains('Pokedex').click().wait(500)
    cy.contains('Bulbasaur')
    cy.contains('Charmander').click().wait(2000)
    cy.get('[data-cy=PokemonCard]').contains('Charmander')
    cy.contains('Close').click()
    cy.get('[data-cy=PokemonCard]').should('not.exist')
    cy.contains('Home').click()
    cy.url().should('eq', 'http://localhost:3001/')
    cy.contains('Pokémon (an abbreviation for Pocket Monsters in Japan)')
  })
})
